# Generated by Django 4.2 on 2024-08-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('componentes', 'Componentes'), ('laptops', 'Laptops'), ('perifericos', 'Periféricos'), ('monitores', 'Monitores'), ('electronica', 'Electrónica')], max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='productos/')),
            ],
        ),
    ]
